version: "3.9"

services:
  # Eureka-Serveur:
  eurekaserver:
    build: ./EurekaServer
    restart: on-failure
    ports:
      - "8080:8080"

  # Zuul Gateway
  zuulgateway:
    depends_on:
      - eurekaserver
    links:
      - eurekaserver
    build: ./ApiGateway
    restart: on-failure
    environment:
      EUREKA_URI: http://eurekaserver:8080/eureka
    ports:
      - "8079:8079"

  # SPRING Services:
  jwtproject:
    depends_on:
      - dbjwt
      - eurekaserver
    links:
      - dbjwt
      - eurekaserver
    build: ./jwtprj
    restart: on-failure
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaserver:8080/eureka
    ports:
      - "8082:8082"

  constatapp:
    depends_on:
      - dbconstat
      - eurekaserver
    links:
      - dbconstat
      - eurekaserver
    build: ./Constats
    restart: on-failure
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaserver:8080/eureka
    ports:
      - "8081:8081"

  # MYSQL SERVICES:
  dbjwt:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: jwtproject
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    volumes:
      - $HOME/data/db-jwt:/var/lib/mysql

  dbconstat:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: constatapp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    volumes:
      - $HOME/data/db-constat:/var/lib/mysql

  # # Node Services:
  # client-folder:
  #  	depends_on:
  #       - eurekaserver
  #    networks:
  #     - "services"
  #   env_file:
  #     - ./ClientFolder/.env
  #   environment:
  #     PORT: 8083
  #   ports:
  #     - "8083:8083"
  #   build: ./ClientFolder
  #
  rembaccident:
    env_file:
      - ./Rembors/.env
    # depends_on:
    #   - eurekaserver
    environment:
      PORT: 8084
      HOSTNAME: rembaccident
      URL_EU: http://eurekaserver:8080/eureka/
    links:
      - eurekaserver
    ports:
      - "8084:8084"
    build: ./Rembors
