version: "3.9"

services:
  # Eureka-Serveur:
  eurekaserver:
    build: ./EurekaServer
    restart: on-failure
    networks:
      - "services"
    ports:
      - "8080:8080"

  # SPRING Services:
  jwtproject:
    depends_on:
      - dbjwt
      - eurekaserver
    networks:
      - "services"
    build: ./jwtprj
    restart: on-failure
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaserver:8080/eureka
    expose:
      - "8082"

  constatapp:
    depends_on:
      - dbconstat
      - eurekaserver
    networks:
      - "services"
    build: ./Constats
    restart: on-failure
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaserver:8080/eureka
    expose:
      - 8082

  # MYSQL SERVICES:
  dbjwt:
    image: mysql
    restart: always
    networks:
      - "services"
    environment:
      MYSQL_DATABASE: jwtproject
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    volumes:
      - $HOME/data/db-jwt:/var/lib/mysql

  dbconstat:
    image: mysql
    restart: always
    networks:
      - "services"
    environment:
      MYSQL_DATABASE: constatapp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    volumes:
      - $HOME/data/db-constat:/var/lib/mysql

  # # Node Services:
  # client-folder:
  #  	depends_on:
  #       - eurekaserver
  #    networks:
  #     - "services"
  #   env_file:
  #     - ./ClientFolder/.env
  #   environment:
  #     PORT: 8083
  #   ports:
  #     - "8083:8083"
  #   build: ./ClientFolder
  #
  # remb-accident:
  #   env_file:
  #     - ./Rembors/.env
  # depends_on:
  #   - eurekaserver
  # networks:
  #   - "services"
  #   environment:
  #     PORT: 8084
  #   ports:
  #     - "8084:8084"
  #   build: ./Rembors

networks:
  services:
    name: services
    driver: bridge
