version: "3.1"

services:
  # Eureka Serveur:
  # jwtproject:
  #   depends_on:
  #     - constatapp
  #     - jwtproject
  #     - client-folder
  #   build: ./EurekaServer
  #   restart: on-failure
  #   ports:
  #     - "8080:8080"
  #
  # SPRING Services:
  # jwtproject:
  #   depends_on:
  #     - db-jwt
  #   links:
  #     - db-jwt
  #   build: ./jwtprj
  #   restart: on-failure
  #   expose:
  #     - 8082
  #
  # constatapp:
  #   depends_on:
  #     - db-constat
  #   links:
  #     - db-constat
  #   build: ./Constats
  #   restart: on-failure
  #   expose:
  #     - 8082

  # MYSQL SERVICES:
  db-jwt:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: jwtproject
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    expose:
      - "3308"
    volumes:
      - $HOME/data/db-jwt:/var/lib/mysql

  db-constat:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: constatapp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    expose:
      - "3307"
    volumes:
      - $HOME/data/db-constat:/var/lib/mysql

  # Node Services:
  client-folder:
    env_file:
      - ./ClientFolder/.env
    environment:
      PORT: 8083
    ports:
      - "8083:8083"
    # expose:
    #   - "8083"
    build: ./ClientFolder
