version: "3.9"

services:
  # Eureka-Serveur:
  eurekaserver:
    build: ./EurekaServer
    restart: on-failure
    ports:
      - "8080:8080"

  # Zuul Gateway
  apigateway:
    depends_on:
      - eurekaserver
      - jwtproject
    build: ./ApiGateway
    restart: on-failure
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaserver:8080/eureka
    ports:
      - "8079:8079"

  # SPRING Services:
  constatapp:
    depends_on:
      - dbglobal
      - eurekaserver
    build: ./Constats
    restart: on-failure
    environment:
      - db=dbglobal
      - eureka.client.service-url.defaultZone=http://eurekaserver:8080/eureka
    ports:
      - "8081:8081"

  jwtproject:
    depends_on:
      - dbjwt
      - eurekaserver
    build: ./jwtprj
    restart: on-failure
    environment:
      - db=dbjwt
      - eureka.client.service-url.defaultZone=http://eurekaserver:8080/eureka
    ports:
      - "8082:8082"

  collision-service:
    depends_on:
      - dbglobal
      - eurekaserver
    build: ./Collisions
    restart: on-failure
    environment:
      - db=dbglobal
      - eureka.client.service-url.defaultZone=http://eurekaserver:8080/eureka
    ports:
      - "8083:8083"

  devis-service:
    depends_on:
      - dbglobal
      - eurekaserver
    build: ./devis
    restart: on-failure
    environment:
      - db=dbglobal
      - eureka.client.service-url.defaultZone=http://eurekaserver:8080/eureka
    ports:
      - "8084:8084"

  repair-service:
    depends_on:
      - dbglobal
      - eurekaserver
    build: ./reparation
    restart: on-failure
    environment:
      - db=dbglobal
      - eureka.client.service-url.defaultZone=http://eurekaserver:8080/eureka
    ports:
      - "8085:8085"

  remb-service:
    depends_on:
      - dbglobal
      - eurekaserver
    build: ./rembour
    restart: on-failure
    environment:
      - db=dbglobal
      - eureka.client.service-url.defaultZone=http://eurekaserver:8080/eureka
    ports:
      - "8086:8086"

  dossier-service:
    depends_on:
      - dbglobal
      - eurekaserver
    build: ./Dossier
    restart: on-failure
    environment:
      - db=dbglobal
      - eureka.client.service-url.defaultZone=http://eurekaserver:8080/eureka
    ports:
      - "8087:8087"

  # MYSQL SERVICES:
  dbjwt:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: jwtproject
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    volumes:
      - $HOME/data/db-jwt:/var/lib/mysql

  dbglobal:
    image: mysql
    restart: always
    environment:
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    volumes:
      - $HOME/data/db-constat:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

  # Node Services:
  recl-service:
    env_file:
      - ./Reclamation/.env
    depends_on:
      - eurekaserver
    build: ./Reclamation
    environment:
      PORT: 8088
      HOSTNAME: recl-service
      EU_HOST: eurekaserver
    ports:
      - "8088:8088"
