version: "3.9"

services:
  # Eureka-Serveur:
  eurekaserver:
    build: ./EurekaServer
    restart: on-failure
    ports:
      - "8080:8080"

  # Zuul Gateway
  apigateway:
    depends_on:
      - eurekaserver
    build: ./ApiGateway
    restart: on-failure
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaserver:8080/eureka
      - spring.profiles.active=path
      - spring.cloud.gateway.routes[0].uri=http://jwtproject:8082
      - spring.cloud.gateway.routes[0].id=auth-service
      - spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
      # SPRING_CLOUD_GATEWAY_ROUTES[0]_FILTERS[0]: StripPrefix=1
    ports:
      - "8079:8079"

  # SPRING Services:
  jwtproject:
    depends_on:
      - dbjwt
      - eurekaserver
    build: ./jwtprj
    restart: on-failure
    environment:
      - db=dbjwt
      - eureka.client.service-url.defaultZone=http://eurekaserver:8080/eureka
    ports:
      - "8082:8082"

  constatapp:
    depends_on:
      - dbglobal
      - eurekaserver
    build: ./Constats
    restart: on-failure
    environment:
      - db=dbglobal
      - eureka.client.service-url.defaultZone=http://eurekaserver:8080/eureka
    ports:
      - "8081:8081"

  # MYSQL SERVICES:
  dbjwt:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: jwtproject
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    volumes:
      - $HOME/data/db-jwt:/var/lib/mysql

  dbglobal:
    image: mysql
    restart: always
    environment:
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    volumes:
      - $HOME/data/db-constat:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

  # Node Services:
  client-folder:
    env_file:
      - ./ClientFolder/.env
    depends_on:
      - eurekaserver
    build: ./ClientFolder
    environment:
      PORT: 8083
      HOSTNAME: client-folder
      EU_HOST: eurekaserver
    ports:
      - "8083:8083"

  rembaccident:
    env_file:
      - ./Rembors/.env
    depends_on:
      - eurekaserver
    build: ./Rembors
    environment:
      PORT: 8084
      HOSTNAME: rembaccident
      EU_HOST: eurekaserver
    ports:
      - "8084:8084"
