server:
  port: 8080 # Indicate the default PORT where this service will be started

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8080/eureka

spring:
  application:
    name: eureka
