spring:
  application:
    name: zuul-gateway

server:
  port: 8079

eureka:
  instance:
    preferIpAddress: true
    status-page-url-path: actuator/health
  client:
    registerWithEureka: true
    fetchRegistry: true

zuul:
  host.socket-timeout-millis: 3000
  routes:
    discovery-service:
      path: /discovery/**
      serviceId: eureka
    auth-service: #2
      path: /auth/**
      serviceId: auth-service
    constat-service: #1
      path: /con/**
      serviceId: constat-service
    collision-service: #3
      path: /col/**
      serviceId: col-service
    remb-service: #6
      path: /remb/**
      serviceId: remb-service
    devis-service: #4
      path: /devis/**
      service-id: devis-service
    dossier-service: #7
      path: /dossier/**
      service-id: dossier-service
    repair-service: #5
      path: /repair/**
      service-id: repair-service
    recl-service: #8
      path: /recl/**
      service-id: recl-service

springfox:
  documentation:
    swagger:
      v2:
        path: /api/uaa/api-docs

whitelistInternal:
  - method: GET
    path: "/api/**/api-docs"
  - method: GET
    path: "/swagger-ui.html"
  - method: GET
    path: "/swagger-resources/**"

management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: "*"
