spring:
  application:
    name: zuul-gateway

server:
  port: 8079

eureka:
  instance:
    preferIpAddress: true
    health-check-url-path: /actuator/health
  client:
    registerWithEureka: true
    fetchRegistry: true

zuul:
  host.socket-timeout-millis: 3000
  routes:
    auth-service:
      path: /auth/*
      serviceId: auth-service
    constat-service:
      path: /c/*
      serviceId: constat-service

springfox:
  documentation:
    swagger:
      v2:
        path: /api/uaa/api-docs

whitelistInternal:
  - method: GET
    path: '/api/**/api-docs'
  - method: GET
    path: '/swagger-ui.html'
  - method: GET
    path: '/swagger-resources/**'
