spring:
  application:
    name: zuul-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: constat-service
          uri: constat-service
          predicates:
          - path=/constat/**

        - id: rembor
          uri: rembor
          predicates:
          - Path=/accident/**

        - id: colission
          uri: colission
          predicates:
          - Path=/colission/**

        - id: client-folder
          uri: client-folder
          predicates:
          - Path=/client/**

server:
  port: 8079

eureka:
  instance:
    preferIpAddress: true
    health-check-url-path: /actuator/health
  client:
    registerWithEureka: true
    fetchRegistry: true

zuul:
  host.socket-timeout-millis: 3000


springfox:
  documentation:
    swagger:
      v2:
        path: /api/uaa/api-docs

whitelistInternal:
  - method: GET
    path: '/api/**/api-docs'
  - method: GET
    path: '/swagger-ui.html'
  - method: GET
    path: '/swagger-resources/**'
