spring:
  application:
    name: zuul-gateway

server:
  port: 8079

eureka:
  instance:
    preferIpAddress: true
    status-page-url-path: actuator/health
  client:
    registerWithEureka: true
    fetchRegistry: true

zuul:
  host.socket-timeout-millis: 3000
  routes:
    discovery-service:
      path: /discovery
      serviceId: eureka
    auth-service:
      path: /auth/**
      serviceId: auth-service
    constat-service:
      path: /con/**
      serviceId: constat-service
    collision-service:
      path: /col/**
      serviceId: col-service
    remb-service:
      path: /remb/**
      serviceId: remb-service
    devis-service:
      path: /devis/**
      service-id: devis-service
    client-service:
      path: /client/**
      service-id: client-service
    repair-service:
      path: /repair/**
      service-id: repair-service
    recl-service:
      path: /recl/**
      service-id: recl-service

springfox:
  documentation:
    swagger:
      v2:
        path: /api/uaa/api-docs

whitelistInternal:
  - method: GET
    path: '/api/**/api-docs'
  - method: GET
    path: '/swagger-ui.html'
  - method: GET
    path: '/swagger-resources/**'
