spring:
    application:
        name: auth-service
    datasource:
        url: jdbc:mysql://localhost:3308/jwtproject?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
        username: root
        password: root
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                format_sql: true
server:
    port: 8082

eureka:
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8080/eureka/
        healthcheck:
            enabled: true
        lease:
            duration: 5

management:
    security:
        enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.

#logging:
#    level:
#        com.example.howtodoinjava: DEBUG
