spring:
    application:
        name: auth-service
    datasource:
        url: jdbc:mysql://${db}:3308/jwtproject?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
        username: root
        password: root
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                format_sql: true
server:
    port: 8082

eureka:
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
#        prefer-ip-address: true
        status-page-url-path: actuator/health
        hostname: localhost
    client:
        healthcheck:
            enabled: true
        lease:
            duration: 5

management:
    security:
        enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.

#logging:
#    level:
#        com.example.howtodoinjava: DEBUG
